# Generated by Django 3.0 on 2020-05-19 15:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('ilrifnl_field', models.FloatField()),
                ('suid', models.FloatField()),
                ('bedr', models.FloatField()),
                ('sdra', models.CharField(max_length=254, null=True)),
                ('sdra_descr', models.CharField(max_length=254, null=True)),
                ('prop', models.IntegerField()),
                ('prid', models.CharField(max_length=254, null=True)),
                ('phaq', models.FloatField()),
                ('phkc', models.FloatField()),
                ('exna', models.FloatField()),
                ('exck', models.FloatField()),
                ('cecs', models.FloatField()),
                ('drai', models.CharField(max_length=254, null=True)),
                ('drai_descr', models.CharField(max_length=254, null=True)),
                ('rdep', models.CharField(max_length=254, null=True)),
                ('rdep_descr', models.CharField(max_length=254, null=True)),
                ('lith', models.CharField(max_length=254, null=True)),
                ('slop', models.IntegerField()),
                ('reli', models.IntegerField()),
                ('soil', models.CharField(max_length=254, null=True)),
                ('sid', models.IntegerField()),
                ('clay', models.CharField(max_length=254, null=True)),
                ('clay_descr', models.CharField(max_length=254, null=True)),
                ('text', models.CharField(max_length=254, null=True)),
                ('text_descr', models.CharField(max_length=254, null=True)),
                ('rslo', models.CharField(max_length=254, null=True)),
                ('rslo_descr', models.CharField(max_length=254, null=True)),
                ('lndf', models.CharField(max_length=254, null=True)),
                ('lndf_descr', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
