# Generated by Django 3.0.8 on 2020-07-11 18:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_soils'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilPH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('ken2_field', models.FloatField()),
                ('suid', models.FloatField()),
                ('phaq', models.FloatField()),
                ('phkc', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
