# Generated by Django 3.0.8 on 2020-07-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_soilph'),
    ]

    operations = [
        migrations.CreateModel(
            name='crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
                ('rainfall', models.CharField(max_length=254, null=True)),
                ('ph', models.CharField(max_length=254, null=True)),
                ('temperature', models.CharField(max_length=254, null=True)),
                ('humidity', models.CharField(max_length=254, null=True)),
                ('drainage', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=254, null=True)),
                ('jan', models.CharField(max_length=254, null=True)),
                ('feb', models.CharField(max_length=254, null=True)),
                ('mar', models.CharField(max_length=254, null=True)),
                ('apr', models.CharField(max_length=254, null=True)),
                ('may', models.CharField(max_length=254, null=True)),
                ('jun', models.CharField(max_length=254, null=True)),
                ('jul', models.CharField(max_length=254, null=True)),
                ('aug', models.CharField(max_length=254, null=True)),
                ('sep', models.CharField(max_length=254, null=True)),
                ('oct', models.CharField(max_length=254, null=True)),
                ('nov', models.CharField(max_length=254, null=True)),
                ('dec', models.CharField(max_length=254, null=True)),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=254, null=True)),
                ('jan', models.CharField(max_length=254, null=True)),
                ('feb', models.CharField(max_length=254, null=True)),
                ('mar', models.CharField(max_length=254, null=True)),
                ('apr', models.CharField(max_length=254, null=True)),
                ('may', models.CharField(max_length=254, null=True)),
                ('jun', models.CharField(max_length=254, null=True)),
                ('jul', models.CharField(max_length=254, null=True)),
                ('aug', models.CharField(max_length=254, null=True)),
                ('sep', models.CharField(max_length=254, null=True)),
                ('oct', models.CharField(max_length=254, null=True)),
                ('nov', models.CharField(max_length=254, null=True)),
                ('dec', models.CharField(max_length=254, null=True)),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=254, null=True)),
                ('jan', models.CharField(max_length=254, null=True)),
                ('feb', models.CharField(max_length=254, null=True)),
                ('mar', models.CharField(max_length=254, null=True)),
                ('apr', models.CharField(max_length=254, null=True)),
                ('may', models.CharField(max_length=254, null=True)),
                ('jun', models.CharField(max_length=254, null=True)),
                ('jul', models.CharField(max_length=254, null=True)),
                ('aug', models.CharField(max_length=254, null=True)),
                ('sep', models.CharField(max_length=254, null=True)),
                ('oct', models.CharField(max_length=254, null=True)),
                ('nov', models.CharField(max_length=254, null=True)),
                ('dec', models.CharField(max_length=254, null=True)),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.Counties')),
            ],
        ),
    ]
