# Generated by Django 3.0.8 on 2020-07-15 20:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_crops_humidity_rainfall_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crops', models.CharField(max_length=254)),
                ('main_crop', models.CharField(max_length=254)),
                ('other_crop', models.CharField(max_length=254)),
                ('county_nam', models.CharField(max_length=254)),
                ('watering', models.CharField(max_length=254)),
                ('area_km2', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
